### ISSUE TITLE
Documentation cleanup

### ISSUE THREAD

**Issue by fiznool** [flowxo/flowxo-sdk#25]
- EXAMPLES.md: some links are broken
- GRUNT.md: some links are broken
- STEP-BY-STEP-GUIDE.md: formatting errors, some links are broken

It might be better to put these docs files into a separate `/docs` folder. Or better yet, cut and paste them into a wiki.

**Comment by johnmjackson** [comment]
I'm not that keen on GRUNT.md or STEP-BY-STEP-GUIDE.md anyway, I agree
they're more wiki type content.  They're not docs, more like tutorials, all
the content is already covered in the docs.

I'll have a mess about with the SDK docs again soon and get it in order.
