### ISSUE TITLE
Retryable errors should print out a generic message, not the err.message

### ISSUE THREAD

**Issue by johnmjackson** [flowxo/flowxo-sdk#28]
Currently, when a method returns a retryable error (a standard JS `Error` object), the SDK prints the error message out to screen. However, when the method is run for real by Flow XO, a generic error message would be used. The SDK should show this generic message rather than the error's own message property.

**Comment by fiznool** [comment]
@johnmjackson I think this should be made a priority. It really won't be that much work and will help to solve a lot of issues where `Error` objects should be `ServiceError`s.

**Comment by johnmjackson** [comment]
I agree.


John Jackson, Managing Director
j <john.jackson@flgtechnology.co.uk>ohn.jackson@flgtechnology.co.uk
01282 798545

FLG Business Technology Limited is registered in England and Wales
number 5289571 at Ribble Court, 1 Mead Way, Padiham BB12 7NG.

**Comment by fiznool** [comment]
Closed via #46
